table MEDIDAS
	lineageTag: 31569037-45d5-4fca-9ab0-ee7a4a831a73

	measure Net_Amount = ```
			[T_Amount] + [T_Discount]
			
			
			
			```
		formatString: $#,##0.0;-$#,##0.0;-
		lineageTag: fd26c399-364b-420b-b9f0-4a7119c8781f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure T_Amount = ```
			/*CALCULATE( SUM(FACT_SALES_LINES[Amount_Invoiced]),FACT_SALES_LINES[Amount_Invoiced]>0)*/SUM('H_VENTAS DETALLE'[Amount_Invoiced])
			
			```
		formatString: "$#,##0.0;-$#,##0.0;-  "
		lineageTag: e4465e9a-e7ae-4981-8527-1ce5e301240f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure T_Discount = sum('H_VENTAS DETALLE'[Discount])
		formatString: $#,##0.0;-$#,##0.0;-
		lineageTag: 972a0de2-5303-4845-b5ee-1ab251863acd

		annotation PBI_FormatHint = {"isCustom":true}

	measure RevenuePerInvoice = ```
			DIVIDE(
			    [T_Amount], 
			    DISTINCTCOUNT('H_VENTAS DETALLE'[Quantity_invoiced]), 
			    0
			)
			```
		formatString: $#,##0.00;-$#,##0.00;-
		lineageTag: dec15605-8732-4275-a4f4-0762a2dc2de4

		annotation PBI_FormatHint = {"isCustom":true}

	measure BlankCard = 1
		formatString: 0
		lineageTag: 0754b72f-c224-4fa4-a52c-408cf000cea4

	measure Ret_Rate = [Net_Amount] / [T_Amount]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 51478380-3d62-426e-a347-a4e81099930e

	measure Q_INvoiced = Sum('H_VENTAS DETALLE'[Amount_Invoiced])
		formatString: 0
		lineageTag: b4888403-7a38-4d82-8004-e2518deeea7a

	measure Q_Trans = DISTINCTCOUNT('H_VENTAS DETALLE'[cust_trxID])
		formatString: 0
		lineageTag: 165d1534-195c-4d5c-8067-f32d827ecb2d

	measure 'Top 5 costumer' = ```
			
			var TopNcostumers=
			   TOPN(
			       5,
			        ALLSELECTED(OthercostumerTable),
			        [Net_Amount]
			
			       ) 
			 var amountNcosturmerK=
			      CALCULATE([Net_Amount],
			      KEEPFILTERS(TopNcostumers)
			      )
			 var amountNcosturmer=
			      CALCULATE([Net_Amount],
			      (TopNcostumers)
			      )
			 var amounntT=
			        CALCULATE(
			               [Net_Amount],
			                ALLSELECTED(OthercostumerTable[ACCOUNT_NAME])
			        )
			 var result=
			          IF(
			              SELECTEDVALUE(OthercostumerTable[ACCOUNT_NAME])="OTROS",amounntT-amountNcosturmer,
			              IF(
			                  ISINSCOPE(OthercostumerTable[ACCOUNT_NAME]),amountNcosturmerK,
			                   amounntT
			              )
			          )
			              
			RETURN result
			```
		lineageTag: a1261585-b91f-4074-9ac9-0260e6b1097f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ranking = ```
			
			 IF( [Top 5 costumer]<> BLANK(),
			   
			  RANKX(
			      TOPN(
			         5,All(OthercostumerTable[ACCOUNT_NAME]),
			      [Net_Amount]
			      ),
			      [Net_Amount]
			  ),BLANK()
			 )
			```
		formatString: 0
		lineageTag: c68e4512-761a-45a9-9c08-47e247a1b3bf

	measure RankingT =
			
			RANKX(
			ALL(DIM_CLIENTES[ACCOUNT_NAME]),
			   [Net_Amount]
			   )
		formatString: 0
		lineageTag: 5e07c248-135b-47a4-b345-1376fe2965dc

	measure MedidaDrillThrough = ```
			
			
			IF(
			    ISFILTERED('H_VENTAS DETALLE'[Description]),
			    VAR CantidadSeleccionada = COUNTROWS(VALUES('H_VENTAS DETALLE'[Description]))
			    RETURN 
			        IF(
			            CantidadSeleccionada = 1,"Producto Filtrado: "&
			            SELECTEDVALUE('H_VENTAS DETALLE'[Description]),
			            ""
			        ),
			    ""
			)
			
			
			
			/*IF(
			    ISFILTERED('H_VENTAS DETALLE'[Description]),
			    CONCATENATEX(
			        VALUES('H_VENTAS DETALLE'[Description]),     // Selecciona todos los valores únicos
			        'H_VENTAS DETALLE'[Description],
			        ", "                            // Delimitador entre los valores
			    ),
			    ""
			)*/
			
			/*IF(
			    ISFILTERED('H_VENTAS DETALLE'[Description]),
			    SELECTEDVALUE('H_VENTAS DETALLE'[Description]),
			    ""
			)*/
			
			
			
			```
		lineageTag: 694c1501-be45-40b4-82ff-1e4a629d3c5a

	measure ValorTextoVisible = ```
			
			IF(
			    ISBLANK(SELECTEDVALUE('DIM_PUNTOS DE DISTRIBUCION'[FULL_SITE_NAME])),
			    "PENDIENTE",  // O puedes usar NA o cualquier otro texto que consideres adecuado
			    SELECTEDVALUE('DIM_PUNTOS DE DISTRIBUCION'[FULL_SITE_NAME])
			)
			
			```
		lineageTag: c1c6fe8f-02c6-4662-9a62-429059f98b06

	measure PrecioUnitario = FORMAT(, "$#,##0.0")
		lineageTag: 1e6d106a-8cfe-4099-b270-b5bb6ee8cf79

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

